### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by narate**
Just add Dockerfile

### CODE REVIEW

**Comment by dtinth** [comment]
Thanks for the pull request, but I think the actual development of the platform is in this repository &rarr; https://github.com/ndidplatform/ndid

thankyou

**Comment by dtinth** [comment]
I’m not sure though… @AnuchitO is this repository still being used? (I assume it is not because I also saw the API code in `ndid` project.) If not, should we archive this repository?

**Comment by zensus** [comment]
This issue was moved to ndidplatform/ndid#18

**Comment by zensus** [comment]
This issue was moved to ndidplatform/ndid#19

**Pull request merged**
